language: java
jdk:
- oraclejdk8
sudo: false
before_deploy: mvn clean verify
deploy:
  skip_cleanup: true
  provider: lambda
  region: us-east-1
  function_name:
    develop: Master-Scheduler-dev
    uat: Master-Scheduler-uat
    prod: Master-Scheduler-prod
  role:
    develop: arn:aws:iam::649232250620:role/Master-Scheduler-dev
    uat: arn:aws:iam::649232250620:role/Master-Scheduler-uat
    prod: arn:aws:iam::649232250620:role/Master-Scheduler-prod
  module_name: org.sagebionetworks.bridge.scheduler
  handler_name: SchedulerLauncher::launch
  memory_size: 384
  runtime: java8
  timeout: 20
  zip: target/BridgeMasterScheduler-1.0.jar
  on:
    all_branches: true
